=== SviluppoWebAvanzato-Univaq/Specifications_REST/2023/Event_Object_Schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://www.univaq.it/f3i/swa/examples/schema_evento.json",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string"
    },
    "summary": {
      "type": "string"
    },
    "location": {
      "type": "string"
    },
    "start": {
      "type": "string",
      "format": "date-time"
    },
    "end": {
      "type": "string",
      "format": "date-time"
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "attachment": {
      "type": "string",
      "format": "binary"
    },
    "participants": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "e-mail"
          }
        },
        "required": [
          "name",
          "email"
        ],
        "additionalProperties": false
      }
    },
    "recurrence": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer",
          "format": "int32"
        },
        "interval": {
          "type": "integer",
          "format": "int32"
        },
        "until": {
          "type": "string",
          "format": "date-time"
        },
        "frequency": {
          "type": "string",
          "enum": [
            "DAILY",
            "WEEKLY",
            "MONTHLY",
            "YEARLY"
          ]
        }
      },
      "required": [
        "frequency"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "uid",
    "start",
    "end",
    "summary"
  ],
  "additionalProperties": false
}

=== SviluppoWebAvanzato-Univaq/Specifications_REST/2024/Event_Object.json
{
  "uid": "IDabc",
  "summary": "Event IDabc",
  "start": "2024-04-10T13:48:48+02:00",
  "end": "2024-04-10T13:48:48.295207+02:00",
  "attachment": "Y2lhbyBhIHR1dHRp",
  "categories": ["a","b"],
  "participants": [
    {
      "name": "Pinco Pallino #0",
      "email": "pinco.pallino0@univaq.it"
    },
    {
      "name": "Pinco Pallino #1",
      "email": "pinco.pallino1@univaq.it"
    }
  ],
  "recurrence": {
    "interval": 2,
    "until": "2024-06-10T13:48:00+02:00",
    "frequency": "WEEKLY"
  }
}
